// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	model "gin-demo/model"

	mock "github.com/stretchr/testify/mock"
)

// UserService is an autogenerated mock type for the UserService type
type UserService struct {
	mock.Mock
}

// GetUserByEmail provides a mock function with given fields: email
func (_m *UserService) GetUserByEmail(email string) (*model.UserData, error) {
	ret := _m.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 *model.UserData
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*model.UserData, error)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(string) *model.UserData); ok {
		r0 = rf(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserData)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserById provides a mock function with given fields: id
func (_m *UserService) GetUserById(id string) (*model.UserData, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserById")
	}

	var r0 *model.UserData
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*model.UserData, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *model.UserData); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserData)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUsers provides a mock function with given fields: email
func (_m *UserService) GetUsers(email string) []model.UserData {
	ret := _m.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 []model.UserData
	if rf, ok := ret.Get(0).(func(string) []model.UserData); ok {
		r0 = rf(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.UserData)
		}
	}

	return r0
}

// Login provides a mock function with given fields: loginRequest
func (_m *UserService) Login(loginRequest *model.UserLoginRequest) (*model.UserLoginResponse, error) {
	ret := _m.Called(loginRequest)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *model.UserLoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.UserLoginRequest) (*model.UserLoginResponse, error)); ok {
		return rf(loginRequest)
	}
	if rf, ok := ret.Get(0).(func(*model.UserLoginRequest) *model.UserLoginResponse); ok {
		r0 = rf(loginRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserLoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.UserLoginRequest) error); ok {
		r1 = rf(loginRequest)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Logout provides a mock function with given fields: logoutRequest
func (_m *UserService) Logout(logoutRequest *model.UserLogoutRequest) (*model.UserLogoutResponse, error) {
	ret := _m.Called(logoutRequest)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 *model.UserLogoutResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.UserLogoutRequest) (*model.UserLogoutResponse, error)); ok {
		return rf(logoutRequest)
	}
	if rf, ok := ret.Get(0).(func(*model.UserLogoutRequest) *model.UserLogoutResponse); ok {
		r0 = rf(logoutRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserLogoutResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.UserLogoutRequest) error); ok {
		r1 = rf(logoutRequest)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: user
func (_m *UserService) Register(user *model.User) error {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.User) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserService creates a new instance of UserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserService {
	mock := &UserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
